output_dir: results/1_nodes_batchsize_1 # $output_dir

mlperf:
    org: LBNL
    division: closed
    status: onprem
    platform: SUBMISSION_PLATFORM_PLACEHOLDER

data:
    name: cosmo
    data_dir: /ccs/home/mrowan/scratch/cosmoUniverse_2019_05_4parE_tf # $data_dir
    n_train: 510
    n_valid: 18
    sample_shape: [128, 128, 128, 4]
    batch_size: 1 # $BATCHSIZE
    n_epochs: 16
    shard: True
    apply_log: True
    prefetch: 0
    n_parallel_reads: 4

model:
    name: cosmoflow
    input_shape: [128, 128, 128, 4]
    target_size: 4
    conv_size: 32
    fc1_size: 128
    fc2_size: 64
    hidden_activation: LeakyReLU
    pooling_type: MaxPool3D
    dropout: 0.5

optimizer:
    name: SGD
    momentum: 0.9

lr_schedule:
    # Standard linear LR scaling configuration
    base_lr: 0.001
    scaling: linear
    base_batch_size: 64
    n_warmup_epochs: 4

    # Learning rate decay schedule
    decay_schedule:
        32: 0.25
        64: 0.125

train:
    loss: mse
    metrics: ['mae']
    target_mae: 0.124
